### ISSUE TITLE
Miro / Mural version of the open ethic canvas

### ISSUE THREAD

**Issue by visenger** [OpenEthicsAI/Canvas#1]
Great work on your canvas! Congratulation!
Quick question: would it be possible to provide Miro and Mural template boards for the ethics canvas?

Thank you in advance!

**Comment by OpenEthicsAI** [comment]
> 
> 
> Great work on your canvas! Congratulation! Quick question: would it be possible to provide Miro and Mural template boards for the ethics canvas?
> 
> Thank you in advance!

Yes @visenger, that would be great, indeed. Thank you! Would you volunteer to help us in making one?

**Comment by nikiluk** [comment]
Hi @visenger there's also a Notion template that I've created. Feel free to use it https://openethics.notion.site/The-Open-Ethics-Canvas-31f5c02b41cc4962b746c3cf1d122330
